sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: deps=low

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ "$deps" = "low" ]]; then composer update --prefer-lowest --prefer-stable; else composer install --prefer-dist; fi

script:
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpunit
